[2023-04-17T08:50:21.762-0300] {processor.py:153} INFO - Started process (PID=80533) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:50:21.763-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T08:50:21.764-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:50:21.764-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:50:21.776-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:50:21.776-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T08:50:21.776-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:50:21.776-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T08:50:21.777-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:50:21.781-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-04-17T08:52:16.849-0300] {processor.py:153} INFO - Started process (PID=80737) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:52:16.850-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T08:52:16.851-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:52:16.851-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:52:16.864-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:52:16.864-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T08:52:16.865-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:52:16.865-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T08:52:16.865-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T08:52:16.870-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
