[2023-04-17T08:59:51.463-0300] {processor.py:153} INFO - Started process (PID=81398) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T08:59:51.463-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T08:59:51.464-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:59:51.464-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T08:59:51.465-0300] {logging_mixin.py:137} INFO - [2023-04-17T08:59:51.465-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T08:59:51.466-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T08:59:51.481-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.020 seconds
[2023-04-17T09:00:36.194-0300] {processor.py:153} INFO - Started process (PID=81647) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:00:36.195-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:00:36.195-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:00:36.195-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:00:36.197-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:00:36.196-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:00:36.197-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:00:36.219-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.028 seconds
[2023-04-17T09:01:19.046-0300] {processor.py:153} INFO - Started process (PID=81744) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:19.055-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:01:19.056-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:19.055-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:19.059-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:19.058-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:01:19.060-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:19.087-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.045 seconds
[2023-04-17T09:01:50.060-0300] {processor.py:153} INFO - Started process (PID=81818) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:50.062-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:01:50.063-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:50.063-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:50.066-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:50.065-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:01:50.066-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:01:50.085-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.028 seconds
[2023-04-17T09:02:32.706-0300] {processor.py:153} INFO - Started process (PID=81899) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:02:32.715-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:02:32.716-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:02:32.716-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:02:32.720-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:02:32.719-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:02:32.720-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:02:32.739-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.038 seconds
[2023-04-17T09:03:14.354-0300] {processor.py:153} INFO - Started process (PID=81978) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:14.354-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:03:14.354-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:14.354-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:14.356-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:14.355-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:03:14.356-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:14.371-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.020 seconds
[2023-04-17T09:03:44.777-0300] {processor.py:153} INFO - Started process (PID=82071) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:44.777-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:03:44.778-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:44.778-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:44.779-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:44.778-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:03:44.779-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:03:44.821-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.047 seconds
[2023-04-17T09:04:27.750-0300] {processor.py:153} INFO - Started process (PID=82173) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:04:27.758-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:04:27.759-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:27.759-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:04:27.763-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:27.762-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:04:27.764-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:04:27.786-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.038 seconds
[2023-04-17T09:05:05.960-0300] {processor.py:153} INFO - Started process (PID=82300) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:05.969-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:05:05.970-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:05.969-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:05.973-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:05.972-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py", line 42
    process_task = PythonOperator(task_id = "process", python_callable = process)
                                                                                 ^
IndentationError: unindent does not match any outer indentation level
[2023-04-17T09:05:05.974-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:05.996-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.039 seconds
[2023-04-17T09:05:48.089-0300] {processor.py:153} INFO - Started process (PID=82392) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:48.090-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:05:48.090-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.090-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:48.098-0300] {processor.py:753} INFO - DAG(s) dict_keys(['test_prueba_fer']) retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:05:48.230-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.230-0300] {manager.py:504} INFO - Created Permission View: can delete on DAG:test_prueba_fer
[2023-04-17T09:05:48.246-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.246-0300] {manager.py:504} INFO - Created Permission View: can edit on DAG:test_prueba_fer
[2023-04-17T09:05:48.264-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.263-0300] {manager.py:504} INFO - Created Permission View: can read on DAG:test_prueba_fer
[2023-04-17T09:05:48.264-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.264-0300] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-17T09:05:48.275-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.275-0300] {dag.py:2726} INFO - Creating ORM DAG for test_prueba_fer
[2023-04-17T09:05:48.280-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:48.280-0300] {dag.py:3452} INFO - Setting next_dagrun for test_prueba_fer to 2023-04-16T12:05:48.280027+00:00, run_after=2023-04-17T12:05:48.280027+00:00
[2023-04-17T09:05:48.327-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.242 seconds
[2023-04-17T09:06:27.847-0300] {processor.py:153} INFO - Started process (PID=82499) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:06:27.855-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:06:27.856-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:27.856-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:06:27.871-0300] {processor.py:753} INFO - DAG(s) dict_keys(['test_prueba_fer']) retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:06:27.883-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:27.883-0300] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-17T09:06:27.963-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:27.963-0300] {dag.py:3452} INFO - Setting next_dagrun for test_prueba_fer to 2023-04-17T12:05:48.280027+00:00, run_after=2023-04-18T12:05:48.280027+00:00
[2023-04-17T09:06:27.989-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.145 seconds
[2023-04-17T09:07:07.697-0300] {processor.py:153} INFO - Started process (PID=82592) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:07.699-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:07:07.700-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:07.700-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:07.711-0300] {processor.py:753} INFO - DAG(s) dict_keys(['test_prueba_fer']) retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:07.723-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:07.723-0300] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-17T09:07:07.798-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:07.798-0300] {dag.py:3452} INFO - Setting next_dagrun for test_prueba_fer to 2023-04-17T12:05:48.280027+00:00, run_after=2023-04-18T12:05:48.280027+00:00
[2023-04-17T09:07:07.829-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.135 seconds
[2023-04-17T09:07:43.026-0300] {processor.py:153} INFO - Started process (PID=82655) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:43.034-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:07:43.035-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:43.035-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:43.054-0300] {processor.py:753} INFO - DAG(s) dict_keys(['test_prueba_fer']) retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:07:43.065-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:43.065-0300] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-17T09:07:43.140-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:43.140-0300] {dag.py:3452} INFO - Setting next_dagrun for test_prueba_fer to 2023-04-17T12:05:48.280027+00:00, run_after=2023-04-18T12:05:48.280027+00:00
[2023-04-17T09:07:43.166-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.143 seconds
[2023-04-17T09:08:17.092-0300] {processor.py:153} INFO - Started process (PID=82741) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:08:17.097-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py for tasks to queue
[2023-04-17T09:08:17.098-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:17.098-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:08:17.115-0300] {processor.py:753} INFO - DAG(s) dict_keys(['test_prueba_fer']) retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py
[2023-04-17T09:08:17.182-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:17.182-0300] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-17T09:08:17.190-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:17.190-0300] {dag.py:3452} INFO - Setting next_dagrun for test_prueba_fer to 2023-04-17T12:05:48.280027+00:00, run_after=2023-04-18T12:05:48.280027+00:00
[2023-04-17T09:08:17.208-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_prueba.py took 0.118 seconds
