[2023-04-23T16:01:27.173-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_prueba_fer.save scheduled__2023-04-22T19:01:19.933573+00:00 [queued]>
[2023-04-23T16:01:27.176-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_prueba_fer.save scheduled__2023-04-22T19:01:19.933573+00:00 [queued]>
[2023-04-23T16:01:27.176-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:01:27.176-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-23T16:01:27.176-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:01:27.190-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): save> on 2023-04-22 19:01:19.933573+00:00
[2023-04-23T16:01:27.192-0300] {standard_task_runner.py:55} INFO - Started process 11620 to run task
[2023-04-23T16:01:27.194-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'test_prueba_fer', 'save', 'scheduled__2023-04-22T19:01:19.933573+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba.py', '--cfg-path', '/tmp/tmp2jj4020b']
[2023-04-23T16:01:27.194-0300] {standard_task_runner.py:83} INFO - Job 27: Subtask save
[2023-04-23T16:01:27.230-0300] {task_command.py:389} INFO - Running <TaskInstance: test_prueba_fer.save scheduled__2023-04-22T19:01:19.933573+00:00 [running]> on host pepino-ThinkPad-E15-Gen-2
[2023-04-23T16:01:27.325-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=faornat@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_prueba_fer
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2023-04-22T19:01:19.933573+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-22T19:01:19.933573+00:00
[2023-04-23T16:01:27.325-0300] {dag_prueba.py:30} INFO - performing saving
[2023-04-23T16:01:27.325-0300] {python.py:177} INFO - Done. Returned value was: None
[2023-04-23T16:01:27.327-0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=test_prueba_fer, task_id=save, execution_date=20230422T190119, start_date=20230423T190127, end_date=20230423T190127
[2023-04-23T16:01:27.366-0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-23T16:01:27.376-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
